repos:
- repo: local
  hooks:
    - id: stubgen
      name: stubgen
      entry: stubgen -m blazefl.core -m blazefl.utils --no-analysis -o src
      language: system
      types: [python]
      pass_filenames: false
      files: ^src/blazefl/.*\.py$
      stages: [pre-commit]
